### ISSUE TITLE
Map Markers

### ISSUE THREAD

**Issue by elu267** [elu267/Group_Project_Unit18#2]
If time permits, want to convert the circle markers to marker clusters similar to Leaflet Day 2 Activity 3

**Comment by wwenash** [comment]
The best I can tell, if we go with the marker clusters (markerClusterGroup()) instead of Layer group(LayerGroup()) we will lose the satellite/gray layers and the Altitude legend.  Do we want to go down the marker cluster path or not?  What are your opinions??

**Comment by sstevener** [comment]
This is what I was asking Drew about today. I'm still not seeing anything that tells me how to create a breaking point where the clusters break into markers that can be color coded. Everything I see ends up with the markers being the default upside-down teardrops. I'm sure there is a way to do it, but I'm pretty sure it requires a better understanding of coding than I have.
