### ISSUE TITLE
Navigation Bar

### ISSUE THREAD

**Issue by elu267** [elu267/Group_Project_Unit18#6]
If time permits, add a navigation bar and link to Meta.html page

**Comment by wwenash** [comment]
Um, should this be: 
-a Horizontal or Vertical Navigation bar?
- should it have a drop down?
- what pages should it go to... just the meta page?

**Comment by elu267** [comment]
I was thinking horizontal but it could be vertical. For now we only have one extra page so it could just be a "button/link" - possible descriptions "More Info" or "About"

**Comment by wwenash** [comment]
Navbar done... and fixed flask to render properly.... May what to change color... LOL
